### ISSUE TITLE
usa setPeso

### ISSUE THREAD

**Issue by lmagarin** [Javierfs94/Reentrega-Lindo-Gatito#2]
https://github.com/Javierfs94/Reentrega-Lindo-Gatito/blob/b6d59f78534077dc8572026875834ea2a54ddd9b/js/Gato.js#L54

**Comment by Javierfs94** [comment]
Lourdes, si utilizo setPeso, el gato no llega a morir y me lanza la excepción del set, ¿cómo puedo solucionarlo?

**Comment by lmagarin** [comment]
¿y por qué no va a morir? Cambias el peso y lo matas. Es ahí donde muere.

**Comment by Javierfs94** [comment]
Si pero al intentar hacer las modificaciones, el peso no se cambiaba. La manera en que logré que si l ohiciera era poniendo: setPeso(this.peso +1) por ejemplo, pero eso me daba el error de que el peso tenía que estar entre 1 y 15 en vez de morirse el gato.
